---                                                                                                             
  - name: copying apache directory                                                                
    copy:                                                                                                             
      src: "{{ apachesrc }}"                                                                                             
      dest: "{{ apachedst }}"                                                                                 
      owner: root                                                                                                       
      group: root                                                                                                       
      mode: '0644'
    notify: restart apache2
    become: True

  - name: copying apache index files
    copy:
      src: "{{ index }}"
      dest: "{{ index_dst }}"
      owner: root
      group: root
      mode: '0644'
    notify: restart apache2
    become: True
